2019-04-25T21:35:59.418836+00:00 app[web.1]: self.callable = self.load()
2019-04-25T21:35:59.418838+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-04-25T21:35:59.418840+00:00 app[web.1]: return self.load_wsgiapp()
2019-04-25T21:35:59.418841+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-04-25T21:35:59.418843+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-04-25T21:35:59.418845+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-04-25T21:35:59.418846+00:00 app[web.1]: __import__(module)
2019-04-25T21:35:59.418848+00:00 app[web.1]: File "/app/app.py", line 32
2019-04-25T21:35:59.418849+00:00 app[web.1]: print form.errors
2019-04-25T21:35:59.418851+00:00 app[web.1]: ^
2019-04-25T21:35:59.418853+00:00 app[web.1]: SyntaxError: Missing parentheses in call to 'print'. Did you mean print(form.errors)?
2019-04-25T21:35:59.419101+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-04-25T21:35:59.452737+00:00 app[web.1]: Exception ignored in: <function _releaseLock at 0x7f1819885158>
2019-04-25T21:35:59.452744+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:35:59.452789+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/logging/__init__.py", line 221, in _releaseLock
2019-04-25T21:35:59.454556+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [11] [INFO] Booting worker with pid: 11
2019-04-25T21:35:59.458735+00:00 app[web.1]: def _releaseLock():
2019-04-25T21:35:59.458738+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
2019-04-25T21:35:59.458980+00:00 app[web.1]: self.reap_workers()
2019-04-25T21:35:59.458986+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2019-04-25T21:35:59.459335+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2019-04-25T21:35:59.459420+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2019-04-25T21:35:59.460174+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [11] [ERROR] Exception in worker process
2019-04-25T21:35:59.460177+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:35:59.460179+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-04-25T21:35:59.460181+00:00 app[web.1]: worker.init_process()
2019-04-25T21:35:59.460183+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-04-25T21:35:59.460184+00:00 app[web.1]: self.load_wsgi()
2019-04-25T21:35:59.460186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-04-25T21:35:59.460188+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-04-25T21:35:59.460190+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-04-25T21:35:59.460191+00:00 app[web.1]: self.callable = self.load()
2019-04-25T21:35:59.460193+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-04-25T21:35:59.460195+00:00 app[web.1]: return self.load_wsgiapp()
2019-04-25T21:35:59.460197+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-04-25T21:35:59.460198+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-04-25T21:35:59.460200+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-04-25T21:35:59.460202+00:00 app[web.1]: __import__(module)
2019-04-25T21:35:59.460203+00:00 app[web.1]: File "/app/app.py", line 32
2019-04-25T21:35:59.460205+00:00 app[web.1]: print form.errors
2019-04-25T21:35:59.460207+00:00 app[web.1]: ^
2019-04-25T21:35:59.460208+00:00 app[web.1]: SyntaxError: Missing parentheses in call to 'print'. Did you mean print(form.errors)?
2019-04-25T21:35:59.460321+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [11] [INFO] Worker exiting (pid: 11)
2019-04-25T21:35:59.494859+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [4] [INFO] Shutting down: Master
2019-04-25T21:35:59.495050+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-04-25T21:35:59.567141+00:00 heroku[web.1]: Process exited with status 3
2019-04-25T21:36:05.778380+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=powerful-escarpment-88433.herokuapp.com request_id=0efbc27f-3237-450c-a1fe-f36f0862c6cf fwd="169.231.147.230" dyno= connect= service= status=503 bytes= protocol=https
2019-04-25T21:39:36.567585+00:00 heroku[web.1]: State changed from crashed to starting
2019-04-25T21:39:41.655359+00:00 heroku[web.1]: Starting process with command `gunicorn app:app --log-file -`
2019-04-25T21:39:44.292778+00:00 app[web.1]: [2019-04-25 21:39:44 +0000] [4] [INFO] Starting gunicorn 19.9.0
2019-04-25T21:39:44.295121+00:00 app[web.1]: [2019-04-25 21:39:44 +0000] [4] [INFO] Listening at: http://0.0.0.0:26165 (4)
2019-04-25T21:39:44.295276+00:00 app[web.1]: [2019-04-25 21:39:44 +0000] [4] [INFO] Using worker: sync
2019-04-25T21:39:44.305812+00:00 app[web.1]: [2019-04-25 21:39:44 +0000] [10] [INFO] Booting worker with pid: 10
2019-04-25T21:39:44.384413+00:00 app[web.1]: [2019-04-25 21:39:44 +0000] [11] [INFO] Booting worker with pid: 11
2019-04-25T21:39:45.511770+00:00 heroku[web.1]: State changed from starting to up
2019-04-25T21:39:46.000107+00:00 app[web.1]: [2019-04-25 21:39:45 +0000] [11] [ERROR] Exception in worker process
2019-04-25T21:39:46.000177+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:39:46.000180+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-04-25T21:39:46.000182+00:00 app[web.1]: worker.init_process()
2019-04-25T21:39:46.000183+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-04-25T21:39:46.000185+00:00 app[web.1]: self.load_wsgi()
2019-04-25T21:39:46.000187+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-04-25T21:39:46.000188+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-04-25T21:39:46.000190+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-04-25T21:39:46.000192+00:00 app[web.1]: self.callable = self.load()
2019-04-25T21:39:46.000193+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-04-25T21:39:46.000195+00:00 app[web.1]: return self.load_wsgiapp()
2019-04-25T21:39:46.000196+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-04-25T21:39:46.000198+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-04-25T21:39:46.000200+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-04-25T21:39:46.000201+00:00 app[web.1]: __import__(module)
2019-04-25T21:39:46.000203+00:00 app[web.1]: File "/app/app.py", line 4, in <module>
2019-04-25T21:39:46.000205+00:00 app[web.1]: from wtforms import Form, TextField, TextAreaField, validators, StringField, SubmitField
2019-04-25T21:39:46.000206+00:00 app[web.1]: ModuleNotFoundError: No module named 'wtforms'
2019-04-25T21:39:46.000402+00:00 app[web.1]: [2019-04-25 21:39:46 +0000] [11] [INFO] Worker exiting (pid: 11)
2019-04-25T21:39:46.010176+00:00 app[web.1]: [2019-04-25 21:39:46 +0000] [10] [ERROR] Exception in worker process
2019-04-25T21:39:46.010180+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:39:46.010182+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-04-25T21:39:46.010184+00:00 app[web.1]: worker.init_process()
2019-04-25T21:39:46.010186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-04-25T21:39:46.010187+00:00 app[web.1]: self.load_wsgi()
2019-04-25T21:39:46.010189+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-04-25T21:39:46.010191+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-04-25T21:39:46.010192+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-04-25T21:39:46.010194+00:00 app[web.1]: self.callable = self.load()
2019-04-25T21:39:46.010196+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-04-25T21:39:46.010197+00:00 app[web.1]: return self.load_wsgiapp()
2019-04-25T21:39:46.010199+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-04-25T21:39:46.010200+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-04-25T21:39:46.010202+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-04-25T21:39:46.010203+00:00 app[web.1]: __import__(module)
2019-04-25T21:39:46.010205+00:00 app[web.1]: File "/app/app.py", line 4, in <module>
2019-04-25T21:39:46.010206+00:00 app[web.1]: from wtforms import Form, TextField, TextAreaField, validators, StringField, SubmitField
2019-04-25T21:39:46.010207+00:00 app[web.1]: ModuleNotFoundError: No module named 'wtforms'
2019-04-25T21:39:46.010650+00:00 app[web.1]: [2019-04-25 21:39:46 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-04-25T21:39:46.191847+00:00 app[web.1]: [2019-04-25 21:39:46 +0000] [4] [INFO] Shutting down: Master
2019-04-25T21:39:46.191961+00:00 app[web.1]: [2019-04-25 21:39:46 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-04-25T21:39:46.360795+00:00 heroku[web.1]: State changed from up to crashed
2019-04-25T21:39:46.346500+00:00 heroku[web.1]: Process exited with status 3
2019-04-25T21:40:30.045325+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=powerful-escarpment-88433.herokuapp.com request_id=a46008ac-5854-4acf-a37f-9cf5560ff47e fwd="169.231.147.230" dyno= connect= service= status=503 bytes= protocol=https
2019-04-25T21:48:04.975377+00:00 heroku[web.1]: State changed from crashed to starting
2019-04-25T21:48:08.395490+00:00 heroku[web.1]: Starting process with command `gunicorn app:app --log-file -`
2019-04-25T21:48:11.765416+00:00 app[web.1]: [2019-04-25 21:48:11 +0000] [4] [INFO] Starting gunicorn 19.9.0
2019-04-25T21:48:11.767081+00:00 app[web.1]: [2019-04-25 21:48:11 +0000] [4] [INFO] Listening at: http://0.0.0.0:11422 (4)
2019-04-25T21:48:11.767206+00:00 app[web.1]: [2019-04-25 21:48:11 +0000] [4] [INFO] Using worker: sync
2019-04-25T21:48:11.772022+00:00 app[web.1]: [2019-04-25 21:48:11 +0000] [10] [INFO] Booting worker with pid: 10
2019-04-25T21:48:11.810540+00:00 app[web.1]: [2019-04-25 21:48:11 +0000] [11] [INFO] Booting worker with pid: 11
2019-04-25T21:48:12.217063+00:00 heroku[web.1]: State changed from starting to up
2019-04-25T21:48:12.825432+00:00 app[web.1]: [2019-04-25 21:48:12 +0000] [10] [ERROR] Exception in worker process
2019-04-25T21:48:12.825469+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:48:12.825471+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-04-25T21:48:12.825473+00:00 app[web.1]: worker.init_process()
2019-04-25T21:48:12.825475+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-04-25T21:48:12.825476+00:00 app[web.1]: self.load_wsgi()
2019-04-25T21:48:12.825478+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-04-25T21:48:12.825479+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-04-25T21:48:12.825481+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-04-25T21:48:12.825483+00:00 app[web.1]: self.callable = self.load()
2019-04-25T21:48:12.825485+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-04-25T21:48:12.825486+00:00 app[web.1]: return self.load_wsgiapp()
2019-04-25T21:48:12.825488+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-04-25T21:48:12.825489+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-04-25T21:48:12.825491+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-04-25T21:48:12.825493+00:00 app[web.1]: __import__(module)
2019-04-25T21:48:12.825494+00:00 app[web.1]: File "/app/app.py", line 4, in <module>
2019-04-25T21:48:12.825496+00:00 app[web.1]: from wtforms import Form, TextField, TextAreaField, validators, StringField, SubmitField
2019-04-25T21:48:12.825498+00:00 app[web.1]: ModuleNotFoundError: No module named 'wtforms'
2019-04-25T21:48:12.825619+00:00 app[web.1]: [2019-04-25 21:48:12 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-04-25T21:48:12.825809+00:00 app[web.1]: [2019-04-25 21:48:12 +0000] [11] [ERROR] Exception in worker process
2019-04-25T21:48:12.825812+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:48:12.825814+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-04-25T21:48:12.825815+00:00 app[web.1]: worker.init_process()
2019-04-25T21:48:12.825817+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-04-25T21:48:12.825818+00:00 app[web.1]: self.load_wsgi()
2019-04-25T21:48:12.825820+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-04-25T21:48:12.825821+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-04-25T21:48:12.825823+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-04-25T21:48:12.825824+00:00 app[web.1]: self.callable = self.load()
2019-04-25T21:48:12.825826+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-04-25T21:48:12.825827+00:00 app[web.1]: return self.load_wsgiapp()
2019-04-25T21:48:12.825828+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-04-25T21:48:12.825830+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-04-25T21:48:12.825831+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-04-25T21:48:12.825832+00:00 app[web.1]: __import__(module)
2019-04-25T21:48:12.825833+00:00 app[web.1]: File "/app/app.py", line 4, in <module>
2019-04-25T21:48:12.825834+00:00 app[web.1]: from wtforms import Form, TextField, TextAreaField, validators, StringField, SubmitField
2019-04-25T21:48:12.825835+00:00 app[web.1]: ModuleNotFoundError: No module named 'wtforms'
2019-04-25T21:48:12.826076+00:00 app[web.1]: [2019-04-25 21:48:12 +0000] [11] [INFO] Worker exiting (pid: 11)
2019-04-25T21:48:12.990650+00:00 app[web.1]: [2019-04-25 21:48:12 +0000] [4] [INFO] Shutting down: Master
2019-04-25T21:48:12.990754+00:00 app[web.1]: [2019-04-25 21:48:12 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-04-25T21:48:13.075354+00:00 heroku[web.1]: State changed from up to crashed
2019-04-25T21:48:13.055823+00:00 heroku[web.1]: Process exited with status 3
